# Generated by Django 5.2.3 on 2025-11-30 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hisabauth', '0002_delete_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Customer table already exists, just connect the model to it
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPoint',
            fields=[
                ('loyalty_point_id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to='customer_dashboard.customer')),
            ],
            options={
                'verbose_name': 'Loyalty Point',
                'verbose_name_plural': 'Loyalty Points',
                'db_table': 'loyalty_point',
            },
        ),
        migrations.CreateModel(
            name='FavoriteShop',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_shops', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Shop',
                'verbose_name_plural': 'Favorite Shops',
                'db_table': 'favorite_shop',
                'unique_together': {('customer', 'shop')},
            },
        ),
    ]


def forwards_func(apps, schema_editor):
    """Skip creating customer table if it already exists"""
    pass


def backwards_func(apps, schema_editor):
    """Handle backward migration"""
    pass
