# Generated by Django 5.2.3 on 2025-12-18 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_dashboard', '0002_remove_business_is_active_remove_business_status'),
        ('customer_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBusinessRelationship',
            fields=[
                ('relationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_relationships', to='business_dashboard.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_relationships', to='customer_dashboard.customer')),
            ],
            options={
                'verbose_name': 'Customer-Business Relationship',
                'verbose_name_plural': 'Customer-Business Relationships',
                'db_table': 'customer_business_relationship',
                'unique_together': {('customer', 'business')},
            },
        ),
    ]
