# Generated by Django 5.2.3 on 2026-01-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0002_customerbusinessrelationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerbusinessrelationship',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer-Business Relationship', 'verbose_name_plural': 'Customer-Business Relationships'},
        ),
        migrations.AddField(
            model_name='customerbusinessrelationship',
            name='pending_due',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Positive means customer owes business, negative means business owes customer', max_digits=12),
        ),
    ]
