# Generated by Django 5.2.3 on 2026-01-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0003_alter_customerbusinessrelationship_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbusinessrelationship',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly credit limit set by business for this customer. 0 means no limit.', max_digits=12),
        ),
    ]
