# Generated by Django 5.2.3 on 2026-01-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0004_customerbusinessrelationship_monthly_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbusinessrelationship',
            name='monthly_limit',
        ),
    ]
