# Generated by Django 5.2.3 on 2026-01-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0005_remove_customerbusinessrelationship_monthly_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Overall monthly spending limit set by customer. 0 means no limit.', max_digits=12),
        ),
    ]
