# Generated by Django 5.2.3 on 2026-01-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0006_customer_monthly_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbusinessrelationship',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Whether the customer has marked this business as favorite'),
        ),
    ]
