# Generated by Django 5.2.3 on 2026-01-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0007_customerbusinessrelationship_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbusinessrelationship',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('deleted', 'Deleted')], default='active', help_text='Status of the connection between customer and business', max_length=20),
        ),
    ]
