# Generated by Django 5.2.3 on 2025-11-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hisabauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
