# Generated by Django 6.0.2 on 2026-02-28 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, help_text='Extra payload (relationship_id, amount, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Null for system-generated notifications (broadcast, reminders, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('connection_request', 'Connection Request'), ('connection_request_accepted', 'Connection Accepted'), ('connection_request_rejected', 'Connection Rejected'), ('connection_deleted', 'Connection Deleted'), ('connection_request_cancelled', 'Connection Cancelled'), ('transaction_added', 'Transaction Added'), ('payment_received', 'Payment Received'), ('due_reminder', 'Due Reminder'), ('monthly_limit_exceeded', 'Monthly Limit Exceeded'), ('bulk_payment_reminder', 'Bulk Payment Reminder'), ('favorite_added', 'Favorite Added'), ('loyalty_points', 'Loyalty Points'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('broadcast', 'Broadcast'), ('system', 'System')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='notificatio_type_f65c28_idx'),
        ),
    ]
