# Generated by Django 5.2.3 on 2025-12-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('pending_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Pending Registration',
                'verbose_name_plural': 'Pending Registrations',
                'db_table': 'pending_registration',
                'ordering': ['-created_at'],
            },
        ),
    ]
