# Generated by Django 5.2.3 on 2025-11-22 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='last_sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
