# Generated by Django 6.0.2 on 2026-03-21 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HybridSwitchRequest',
            fields=[
                ('hybrid_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('business', 'Business'), ('customer', 'Customer')], max_length=20)),
                ('is_business_verified_at_request', models.BooleanField(default=False)),
                ('citizenship_document', models.ImageField(upload_to='verification_documents/hybrid_citizenship/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_hybrid_switch_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hybrid_switch_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hybrid_switch_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='hybrid_swit_user_id_5b3a1a_idx')],
            },
        ),
    ]
