# Generated by Django 5.2.3 on 2026-01-31 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_dashboard', '0007_customerbusinessrelationship_is_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chat_room_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='customer_dashboard.customerbusinessrelationship')),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'db_table': 'chat_room',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('transaction_update', 'Transaction Update'), ('system', 'System Message')], default='text', max_length=20)),
                ('content', models.TextField(help_text='Text content of the message')),
                ('file_url', models.URLField(blank=True, help_text='URL to uploaded file or image (for image/file types)', max_length=500, null=True)),
                ('is_edited', models.BooleanField(default=False, help_text='Whether the message has been edited')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='realtime_chat.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('message_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the status was achieved')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='realtime_chat.message')),
                ('user', models.ForeignKey(help_text='The user for whom this status applies (recipient)', on_delete=django.db.models.deletion.CASCADE, related_name='message_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Status',
                'verbose_name_plural': 'Message Statuses',
                'db_table': 'message_status',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_room', 'created_at'], name='message_chat_ro_c5fae2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='message_sender__8e11cb_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['message', 'user'], name='message_sta_message_8e5cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['user', 'status'], name='message_sta_user_id_2503ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagestatus',
            unique_together={('message', 'user')},
        ),
    ]
