# Generated by Django 5.2.3 on 2025-12-02 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='business',
            name='status',
        ),
    ]
