# Generated by Django 6.0.2 on 2026-02-28 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_dashboard', '0002_remove_business_is_active_remove_business_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessVerificationRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.FileField(help_text='Business shop document (e.g. registration certificate, PAN, license)', upload_to='verification_documents/')),
                ('document_type', models.CharField(default='business_registration', help_text='Type of document submitted', max_length=100)),
                ('note', models.TextField(blank=True, help_text='Optional note from the business owner', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_remarks', models.TextField(blank=True, help_text='Remarks from admin after reviewing the document', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='business_dashboard.business')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Verification Request',
                'verbose_name_plural': 'Business Verification Requests',
                'db_table': 'business_verification_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
