# Generated by Django 6.0.2 on 2026-03-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_dashboard', '0003_businessverificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, help_text='Physical address of the business', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude of business location', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude of business location', max_digits=10, null=True),
        ),
    ]
