# Generated by Django 5.2.3 on 2025-12-18 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_dashboard', '0002_remove_business_is_active_remove_business_status'),
        ('customer_dashboard', '0002_customerbusinessrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCustomerRequest',
            fields=[
                ('business_customer_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_requests', to='business_dashboard.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_requests', to='customer_dashboard.customer')),
            ],
            options={
                'db_table': 'business_customer_request',
                'ordering': ['-created_at'],
                'unique_together': {('business', 'customer')},
            },
        ),
    ]
