# Generated by Django 5.2.3 on 2025-12-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscustomerrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Business Customer Request', 'verbose_name_plural': 'Business Customer Requests'},
        ),
    ]
