# Generated by Django 5.2.3 on 2026-01-03 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_dashboard', '0002_remove_business_is_active_remove_business_status'),
        ('customer_dashboard', '0003_alter_customerbusinessrelationship_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive = customer owes more, Negative = customer paid/refund', max_digits=12)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('payment', 'Payment'), ('credit', 'Credit Given'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], default='purchase', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Description or name of the transaction', max_length=255)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='Date when transaction occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customer_dashboard.customerbusinessrelationship')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='business_dashboard.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='customer_dashboard.customer')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'db_table': 'favorite',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'business')},
            },
        ),
    ]
