# Generated by Django 6.0.2 on 2026-03-02 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_dashboard', '0003_businessverificationrequest'),
        ('customer_dashboard', '0008_customerbusinessrelationship_status'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEsewaAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('esewa_id', models.CharField(help_text='Business eSewa ID (phone number)', max_length=20)),
                ('account_name', models.CharField(help_text='Name on the eSewa account', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esewa_account', to='business_dashboard.business')),
            ],
            options={
                'verbose_name': 'Business eSewa Account',
                'verbose_name_plural': 'Business eSewa Accounts',
                'db_table': 'business_esewa_account',
            },
        ),
        migrations.CreateModel(
            name='EsewaPaymentRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('esewa_ref_id', models.CharField(blank=True, help_text='eSewa transaction reference ID', max_length=100, null=True)),
                ('esewa_product_id', models.CharField(help_text='Unique product ID sent to eSewa', max_length=255)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('verified', 'Verified')], default='initiated', max_length=20)),
                ('esewa_response_data', models.JSONField(blank=True, help_text='Full response data from eSewa', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esewa_payments', to='customer_dashboard.customerbusinessrelationship')),
                ('transaction', models.OneToOneField(blank=True, help_text='Linked internal transaction (created after verification)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esewa_payment', to='transaction.transaction')),
            ],
            options={
                'verbose_name': 'eSewa Payment Record',
                'verbose_name_plural': 'eSewa Payment Records',
                'db_table': 'esewa_payment_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
