# Generated by Django 6.0.2 on 2026-03-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_dashboard', '0003_businessverificationrequest'),
        ('customer_dashboard', '0008_customerbusinessrelationship_status'),
        ('transaction', '0002_businessesewaaccount_esewapaymentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessKhaltiAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('khalti_id', models.CharField(help_text='Business Khalti ID (phone number)', max_length=20)),
                ('account_name', models.CharField(help_text='Name on the Khalti account', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='khalti_account', to='business_dashboard.business')),
            ],
            options={
                'verbose_name': 'Business Khalti Account',
                'verbose_name_plural': 'Business Khalti Accounts',
                'db_table': 'business_khalti_account',
            },
        ),
        migrations.CreateModel(
            name='KhaltiPaymentRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pidx', models.CharField(blank=True, max_length=255, null=True)),
                ('khalti_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_order_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('verified', 'Verified')], default='initiated', max_length=20)),
                ('khalti_response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khalti_payments', to='customer_dashboard.customerbusinessrelationship')),
                ('transaction', models.OneToOneField(blank=True, help_text='Linked internal transaction (created after verification)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='khalti_payment', to='transaction.transaction')),
            ],
            options={
                'verbose_name': 'Khalti Payment Record',
                'verbose_name_plural': 'Khalti Payment Records',
                'db_table': 'khalti_payment_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
